Add error reporting to CLI when database doesn't exist
New output:
```
 halkeye@odin  ~/git/bellows  EZSP_DEVICE=/dev/zigbee bellows devices
 Usage: bellows devices [OPTIONS]

 Error: Invalid value for "-D" / "--database": Path
 "/home/halkeye/.config/bellows/app.db" does not exist.
```